export const TABLE_RESIZE = 'TABLE_RESIZE'
export const CHANGE_TEXT = 'CHANGE_TEXT'
export const SET_STYLES = 'SET_STYLES'
export const CHANGE_STYLES = 'CHANGE_STYLES'
export const CHANGE_TITLE = 'CHANGE_TITLE'
export const OPEN_DATE = 'OPEN_DATE'
